name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Minify static content
        run: |
          # Install dependencies
          npm install terser -g
          
          # Minify JS files
          find . -type f -name '*.js' -exec terser {} -o {} \;
          
          # Minify CSS files
          find . -type f -name '*.css' -exec npx minify {} -o {} \;
          
          # Minify HTML files
          find . -type f -name '*.html' -exec npx html-minifier {} -o {} \;
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
